# Generated by Django 5.1.3 on 2025-01-12 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_customuser_email_delete_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
